export default [
  {
		id: 11,
		title: 'تاریخ برگزاری رویداد PC GAME SHOW 2022 اعلام شد',
		featuredImage: '/img/post (11).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 12,
		title: 'تاریخ رونمایی Final Fantasy 16',
		featuredImage: '/img/post (12).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 1,
		title: 'انتشار بازی باشکوه Elden Ring با آمار فروش باور نکردنی',
		featuredImage: '/img/post (1).png',
		releaseDate: '۱۰ روز پیش',
		modifyDate: '۲ روز پیش',
		comments: [
			{
				id: 1,
				firstname: 'رضا',
				lastname: 'پاک',
				content: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.',
				date: '1400-12-1',
			},
			{
				id: 2,
				firstname: 'رضا',
				lastname: 'پاک',
				content: 'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.',
				date: '1400-12-1',
			},
		],
	},
	{
		id: 2,
		title: 'فروش بازی Horizon Zero Dawn از 20 میلیون نسخه عبور کرد!',
		featuredImage: '/img/post (2).png',
		releaseDate: '۲۳ بهمن ۱۴۰۰',
		modifyDate: '۲۴ بهمن ۱۴۰۰',
	},
	{
		id: 3,
		title: 'منتظر یک NEED FOR SPEED جهان باز موبایلی باشید!',
		featuredImage: '/img/post (3).png',
		releaseDate: '۲ آبان ۱۴۰۰',
	},
	{
		id: 4,
		title: 'ساخت بازی GTA VI رسمی شد!',
		featuredImage: '/img/post (4).png',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 5,
		title: 'احتمال عرضه COD Warzone 2 در اواخر امسال',
		featuredImage: '/img/post (5).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 8,
		title: 'Star Wars یکی از پر‌فروش‌ترین بازی‌های امسال',
		featuredImage: '/img/post (8).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 9,
		title: 'تاریخ احتمالی عرضه God of War Ragnarok',
		featuredImage: '/img/post (9).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 6,
		title: 'احتمال برگزاری رویداد جدید پلی‌استیشن در اواسط این ماه',
		featuredImage: '/img/post (6).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 14,
		title: 'شایعاتی در مورد بازی جدید UBISOFT',
		featuredImage: '/img/post (14).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 10,
		title: 'بروزرسانی بزرگ Gran Turismo 7 منتشر شد!',
		featuredImage: '/img/post (10).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 15,
		title: 'شایعاتی در مورد بازی‌های جدید UBISOFT',
		featuredImage: '/img/post (15).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 7,
		title: 'قابلیت‌های شخصی‌سازی بی‌نظیر Saints Row',
		featuredImage: '/img/post (7).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
  {
		id: 13,
		title: 'مقایسه فروش PS5 و XBOX در سال 2021',
		featuredImage: '/img/post (13).jpg',
		releaseDate: '۱۷ مرداد ۱۴۰۰',
		modifyDate: '۲۰ مرداد ۱۴۰۰',
	},
]
